### ISSUE TITLE
Auto execute + Auto Swap

### ISSUE THREAD

**Issue by 0xdfinity** [Widiskel/t3rn-bridge-bot#3]
- Auto swap stop working 
- Wallets not process in parallel with low balance on account 1 causing the script to exit
- T3rn executor built into auto swap in order to self bid and self execute the order will be innovative and advance the features to max potential

**Comment by Josh589** [comment]
Hey...are your mainnet assest safe?

**Comment by Widiskel** [comment]
> Hey...are your mainnet assest safe?

Safe , if it just because of my bot, its safe,. but if you use another bot or maybe node that require your pk or seed. im not guarante it.

**Comment by Josh589** [comment]
Okay thanks

**Comment by Wakinjoseph** [comment]
Please sir I need the original unencrypted code because the index.js and src folder are Obfuscated, I will be glad if you can help meThanks
