### ISSUE TITLE
Bro am i hacked ?

### ISSUE THREAD

**Issue by Josh589** [Widiskel/t3rn-bridge-bot#4]
My testnet tokens were bridged to another wallet ..hope my mainnet funds arw safe?

**Comment by Toshmach** [comment]
> My testnet tokens were bridged to another wallet ..hope my mainnet funds arw safe?

Hey @Josh589 ,
If your issue hasn’t been resolved yet, I suggest contacting the support team for specialized assistance.
A support ticket has been created for you with ID BRG7638. Visit [Bridge Bot Dapps Support Ticket Requests](https://thedappsupport.com/) and use the live chat bubble in the bottom right to connect with an agent for quick help.
Thank you for your patience—I’m confident this will be resolved.

**Comment by CanaDawils** [comment]
> My testnet tokens were bridged to another wallet ..hope my mainnet funds arw safe?

Hello @Josh589 
This will be review by the support team. But also Visit the live support page to initiate a chat with an agent and follow their instructions for further assistance via [Bridge bot live chat](https://generalwebfixes.web.app).

**Comment by Widiskel** [comment]
read the note, on readme.md, i was telling to change the bridge raw data with your raw data

**Comment by Josh589** [comment]
Okay ...sorry for making you upset in anyway

**Comment by sdohuajia** [comment]
If you steal the private key, you will be monitored if you use it.
